// const products = [
//   {
//     title: {
//       ru: "Омлет с сыром",
//       ua: "Омлет із сиром",
//     },
//     groupBloodNotAllowed: [null, true, false, false, false],
//     categories: ["яйца"],
//     weight: 100,
//     _id: "5d51694802b2373622ff5530",
//     calories: 342,
//     __v: 0,
//   },
//   {
//     title: {
//       ru: "Омлет из яичного порошка",
//       ua: "Омлет з яєчного порошку",
//     },
//     groupBloodNotAllowed: [null, true, false, false, false],
//     categories: ["яйца"],
//     weight: 100,
//     _id: "5d51694802b2373622ff552f",
//     calories: 200,
//     __v: 0,
//   },
//   {
//     title: {
//       ru: "Омлет из взбитых сливок",
//       ua: "Омлет зі збитих вершків",
//     },
//     groupBloodNotAllowed: [null, true, false, false, false],
//     categories: ["яйца"],
//     weight: 100,
//     _id: "5d51694802b2373622ff552e",
//     calories: 257,
//     __v: 0,
//   },
//   {
//     title: {
//       ru: "Омлет",
//       ua: "Ямлет",
//     },
//     groupBloodNotAllowed: [null, true, false, false, false],
//     categories: ["яйца"],
//     weight: 100,
//     _id: "5d51694802b2373622ff552d",
//     calories: 184,
//     __v: 0,
//   },
// ];

// const aaa = products.map((product) => ({
//   product,
//   label: product.title.ru,
// }));

// export default aaa;

const states = {
  AL: "Alabama",
  AK: "Alaska",
  AS: "American Samoa",
  AZ: "Arizona",
  AR: "Arkansas",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DE: "Delaware",
  DC: "District Of Columbia",
  FM: "Federated States Of Micronesia",
  FL: "Florida",
  GA: "Georgia",
  GU: "Guam",
  HI: "Hawaii",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  IA: "Iowa",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  ME: "Maine",
  MH: "Marshall Islands",
  MD: "Maryland",
  MA: "Massachusetts",
  MI: "Michigan",
  MN: "Minnesota",
  MS: "Mississippi",
  MO: "Missouri",
  MT: "Montana",
  NE: "Nebraska",
  NV: "Nevada",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NY: "New York",
  NC: "North Carolina",
  ND: "North Dakota",
  MP: "Northern Mariana Islands",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PW: "Palau",
  PA: "Pennsylvania",
  PR: "Puerto Rico",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VT: "Vermont",
  VI: "Virgin Islands",
  VA: "Virginia",
  WA: "Washington",
  WV: "West Virginia",
  WI: "Wisconsin",
  WY: "Wyoming",
};
const aaa = Object.keys(states).map((value) => ({
  value,
  label: states[value],
}));
export default aaa;
